############################################################################
# custom_boards/blackpill-f411/src/Makefile
############################################################################

include $(TOPDIR)/Make.defs
include Make.defs
include $(TOPDIR)/boards/Board.mk
